(in-package :aoc-tests)
(5am:in-suite aoc-tests)

(5am:test rosetta-example
  (let ((edges '(((:a :b) . 7)
                 ((:a :c) . 9)
                 ((:a :f) . 14)
                 ((:b :c) . 10)
                 ((:b :d) . 15)
                 ((:c :d) . 11)
                 ((:c :f) . 2)
                 ((:d :e) . 6)
                 ((:e :f) . 9)))
        (expected-dists '((:e . 26) (:f . 11) (:d . 20) (:d . 22)
                          (:f . 14) (:c . 9) (:b . 7) (:a . 0)))
        (expected-paths '((:e . :d) (:f . :c) (:d . :c) (:d . :b)
                          (:f . :a) (:c . :a) (:b . :a))))
    (multiple-value-bind (dists paths) (aoc:dijkstra edges :a)
      (5am:is (equal expected-dists dists))
      (5am:is (equal expected-paths paths)))))
